name: Third Workflow

on: push

jobs: 
  run-first-command: 
    runs-on: ubuntu-latest
    steps:
      - name: list files and copy repo
        run: ls
      - uses: actions/checkout@v4
      - name: list files 
        run: ls